### ISSUE TITLE
Home Page: Where do you want to go? Get Error Page

### ISSUE THREAD

**Issue by kchauatadobe** [lamontacrook/aem-pure-headless#2]
1. On the Home Page
2. Scroll down to the bottom
3. Click on any of the Where do you want to go? adventure links
4. Get the Cannot read properties of undefined (reading 'screen') error screen

![Screenshot_4](https://user-images.githubusercontent.com/104858147/207890725-779a9f4c-53be-4bb9-b79b-0a18a4b47e62.png)
![Screenshot_3](https://user-images.githubusercontent.com/104858147/207890827-f58679c7-c846-419a-b8a1-fdf9d843c3cb.png)

**Comment by lamontacrook** [comment]
This has been fixed.
